
/**
 ** MARKER_BEGIN
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2016-12-12 12:49:29.684261
 ** by jchen@ubuntu
 ** MARKER_END
 **/
#ifndef _DEMUX_PROTO_H
#define _DEMUX_PROTO_H

#include <srl.h>

struct _demux_args_t {
	const srl_mwmr_t input;
	const srl_mwmr_t quanti;
	const srl_mwmr_t huffman;
	const srl_mwmr_t output;
};

#define demux_FUNC_NAME(sym) demux_func_ ## sym

#define FUNC(x) void demux_FUNC_NAME(x) (struct _demux_args_t *_func_args)

FUNC(demux);

#ifdef SRL_INMAIN
# undef FUNC
#else
# define GET_ARG(port) ({ \
srl_log_printf( DEBUG, "%s:%d: arg %s = %p\n", __FILE__, __LINE__, #port, _func_args->port ); \
(_func_args->port); \
})
#endif /* SRL_INMAIN */

#endif /* _DEMUX_PROTO_H */
