
/**
 ** MARKER_BEGIN
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2016-12-12 12:49:29.684316
 ** by jchen@ubuntu
 ** MARKER_END
 **/
#ifndef _TG_PROTO_H
#define _TG_PROTO_H

#include <srl.h>

struct _tg_args_t {
	const srl_mwmr_t output;
};

#define tg_FUNC_NAME(sym) tg_func_ ## sym

#define FUNC(x) void tg_FUNC_NAME(x) (struct _tg_args_t *_func_args)

FUNC(tg);
FUNC(bootstrap);

#ifdef SRL_INMAIN
# undef FUNC
#else
# define GET_ARG(port) ({ \
srl_log_printf( DEBUG, "%s:%d: arg %s = %p\n", __FILE__, __LINE__, #port, _func_args->port ); \
(_func_args->port); \
})
#endif /* SRL_INMAIN */

#endif /* _TG_PROTO_H */
