
/**
 ** MARKER_BEGIN
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2016-12-12 12:49:29.684144
 ** by jchen@ubuntu
 ** MARKER_END
 **/
#ifndef _VLD_PROTO_H
#define _VLD_PROTO_H

#include <srl.h>

struct _vld_args_t {
	const srl_mwmr_t input;
	const srl_mwmr_t huffman;
	const srl_mwmr_t output;
};

#define vld_FUNC_NAME(sym) vld_func_ ## sym

#define FUNC(x) void vld_FUNC_NAME(x) (struct _vld_args_t *_func_args)

FUNC(vld);

#ifdef SRL_INMAIN
# undef FUNC
#else
# define GET_ARG(port) ({ \
srl_log_printf( DEBUG, "%s:%d: arg %s = %p\n", __FILE__, __LINE__, #port, _func_args->port ); \
(_func_args->port); \
})
#endif /* SRL_INMAIN */

#endif /* _VLD_PROTO_H */
