
/**
 ** MARKER_BEGIN
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2016-12-05 21:10:45.979044
 ** by jchen@ubuntu
 ** MARKER_END
 **/

#include <srl.h>
#include <srl_private_types.h>

#define SRL_INMAIN
# include "consumer_proto.h"
# include "producer_proto.h"
#undef SRL_INMAIN

static srl_barrier_s _start_barrier   = SRL_BARRIER_INITIALIZER(2);
static unsigned char cons0_stack[2048] ;
static unsigned char fifo0_buf[128]   ;
static unsigned char prod0_stack[2048] ;
static srl_mwmr_status_s fifo0_status = SRL_MWMR_STATUS_INITIALIZER(  32,    4);
#ifdef SRL_MWMR_USE_SEPARATE_LOCKS // ;
static srl_mwmr_lock_t fifo0_lock     = SRL_MWMR_LOCK_INITIALIZER;
#endif // ;
const srl_mwmr_s fifo0         = SRL_MWMR_INITIALIZER(  32,    4,            fifo0_buf, &fifo0_status, "fifo0", &fifo0_lock);
static const struct _consumer_args_t cons0_args = {
	.input = (const srl_mwmr_t)&fifo0,
};
static const struct _producer_args_t prod0_args = {
	.output = (const srl_mwmr_t)&fifo0,
};
static srl_task_s cons0               = SRL_TASK_INITIALIZER(0, consumer_FUNC_NAME(cons_func), 2048, cons0_stack, &cons0_args, "cons0", 0x0, 0);
static srl_task_s prod0               = SRL_TASK_INITIALIZER(0, producer_FUNC_NAME(prod_func), 2048, prod0_stack, &prod0_args, "prod0", 0x0, 0);
static srl_task_s * const cpu_task_list[2] = {&prod0, &cons0, };
static const srl_cpudesc_s cpu_cpu_desc = SRL_CPUDESC_INITIALIZER(   2, cpu_task_list, 0x0, 0);
static const srl_mwmr_s const * const all_mwmr[2] = {&fifo0, NULL };
static srl_task_s* const all_task[3]  = {&cons0, &prod0, NULL };
static const srl_cpudesc_s *cpu_desc_list[] = {&cpu_cpu_desc, NULL};
const srl_appdesc_s app_desc   = SRL_APPDESC_INITIALIZER(   2, cpu_desc_list, all_mwmr, all_task, &_start_barrier, 0x0, 0);

