
/**
 ** MARKER_BEGIN
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2016-12-05 21:10:45.978326
 ** by jchen@ubuntu
 ** MARKER_END
 **/

#include <srl.h>
#include <srl_private_types.h>



void hw_init()
{
}
