
/**
 ** MARKER_BEGIN
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2016-12-05 21:10:45.978567
 ** by jchen@ubuntu
 ** MARKER_END
 **/
#ifndef _PRODUCER_PROTO_H
#define _PRODUCER_PROTO_H

#include <srl.h>

struct _producer_args_t {
	const srl_mwmr_t output;
};

#define producer_FUNC_NAME(sym) producer_func_ ## sym

#define FUNC(x) void producer_FUNC_NAME(x) (struct _producer_args_t *_func_args)

FUNC(prod_func);

#ifdef SRL_INMAIN
# undef FUNC
#else
# define GET_ARG(port) ({ \
srl_log_printf( DEBUG, "%s:%d: arg %s = %p\n", __FILE__, __LINE__, #port, _func_args->port ); \
(_func_args->port); \
})
#endif /* SRL_INMAIN */

#endif /* _PRODUCER_PROTO_H */
